server:
  port: 9000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/chkcovid
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL11Dialect
  freemarker:
    expose-request-attributes: true
loger:
  level:
    root: DEBUG