server:
  port: 8091
  servlet:
    context-path: /check
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/cov_prod_copy
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL11Dialect
    show-sql: true
  freemarker:
    expose-request-attributes: true
loger:
  level:
    root: INFO